apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::757101550911:role/UdacityFlaskDeployCBKubectlRole
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-08-25T08:54:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1646"
  uid: 2435cf3f-3eb0-4cbf-861d-34436de6098a
